BUILDSCAD_PROJECT=openRack
BUILDSCAD_VERSION=0.2.3
BUILDSCAD_AUTHOR=dduxx
BUILDSCAD_ASSEMBLIES=scad/assemblies/rack_studs/bracket.scad,\
    scad/assemblies/rack_studs/nut.scad,\
    scad/assemblies/hdd/sled.scad[SLED_TYPE="default"],\
    scad/assemblies/hdd/sled.scad[SLED_TYPE="2_5_adapter"],\
    scad/assemblies/faceplate/jbod/jbod.scad[JBOD_RACK_TYPE="NINETEEN_INCH";SECTION="LEFT"],\
    scad/assemblies/faceplate/jbod/jbod.scad[JBOD_RACK_TYPE="NINETEEN_INCH";SECTION="MIDDLE"],\
    scad/assemblies/faceplate/jbod/jbod.scad[JBOD_RACK_TYPE="NINETEEN_INCH";SECTION="RIGHT"],\
    scad/assemblies/faceplate/jbod/jbod.scad[JBOD_RACK_TYPE="TEN_INCH";JBOD_SECTIONS=2;SECTION="LEFT";DRIVES_PER_SECTION=2],\
    scad/assemblies/faceplate/jbod/jbod.scad[JBOD_RACK_TYPE="TEN_INCH";JBOD_SECTIONS=2;SECTION="RIGHT";DRIVES_PER_SECTION=2],\
    scad/assemblies/faceplate/join_key.scad,\
    scad/assemblies/faceplate/slot_mount/slot_mount.scad[SLOT_MOUNT_RACK_TYPE="NINETEEN_INCH";SECTION="LEFT"],\
    scad/assemblies/faceplate/slot_mount/slot_mount.scad[SLOT_MOUNT_RACK_TYPE="NINETEEN_INCH";SECTION="MIDDLE"],\
    scad/assemblies/faceplate/slot_mount/slot_mount.scad[SLOT_MOUNT_RACK_TYPE="NINETEEN_INCH";SECTION="RIGHT"],\
    scad/assemblies/faceplate/slot_mount/slot_mount.scad[SLOT_MOUNT_RACK_TYPE="TEN_INCH";SLOT_MOUNT_SECTIONS=2;SECTION="LEFT"],\
    scad/assemblies/faceplate/slot_mount/slot_mount.scad[SLOT_MOUNT_RACK_TYPE="TEN_INCH";SLOT_MOUNT_SECTIONS=2;SECTION="RIGHT"],\
    scad/assemblies/power/retention_nut.scad,\
    scad/assemblies/faceplate/patch_panel/patch_panel.scad[PATCH_PANEL_RACK_TYPE="NINETEEN_INCH";PATCH_PANEL_SECTION="LEFT"],\
    scad/assemblies/faceplate/patch_panel/patch_panel.scad[PATCH_PANEL_RACK_TYPE="NINETEEN_INCH";PATCH_PANEL_SECTION="MIDDLE"],\
    scad/assemblies/faceplate/patch_panel/patch_panel.scad[PATCH_PANEL_RACK_TYPE="NINETEEN_INCH";PATCH_PANEL_SECTION="RIGHT"],\
    scad/assemblies/faceplate/patch_panel/patch_panel.scad[PATCH_PANEL_RACK_TYPE="TEN_INCH";PATCH_PANEL_SECTIONS=2;PATCH_PANEL_SECTION="LEFT";JACKS_PER_SECTION=5],\
    scad/assemblies/faceplate/patch_panel/patch_panel.scad[PATCH_PANEL_RACK_TYPE="TEN_INCH";PATCH_PANEL_SECTIONS=2;PATCH_PANEL_SECTION="RIGHT";JACKS_PER_SECTION=5],\
    scad/assemblies/faceplate/fan/fan_panel.scad[FAN_PANEL_RACK_TYPE="NINETEEN_INCH";FAN_PANEL_SECTION="LEFT";FAN_SIZE_MM=40],\
    scad/assemblies/faceplate/fan/fan_panel.scad[FAN_PANEL_RACK_TYPE="NINETEEN_INCH";FAN_PANEL_SECTION="MIDDLE";FAN_SIZE_MM=40],\
    scad/assemblies/faceplate/fan/fan_panel.scad[FAN_PANEL_RACK_TYPE="NINETEEN_INCH";FAN_PANEL_SECTION="RIGHT";FAN_SIZE_MM=40],\
    scad/assemblies/faceplate/fan/fan_panel.scad[FAN_PANEL_RACK_TYPE="TEN_INCH";FAN_PANEL_SECTIONS=2;FAN_PANEL_SECTION="LEFT";FAN_SIZE_MM=40;FANS_PER_SECTION=2],\
    scad/assemblies/faceplate/fan/fan_panel.scad[FAN_PANEL_RACK_TYPE="TEN_INCH";FAN_PANEL_SECTIONS=2;FAN_PANEL_SECTION="RIGHT";FAN_SIZE_MM=40;FANS_PER_SECTION=2],\
    scad/assemblies/faceplate/fan/fan_panel.scad[FAN_PANEL_RACK_TYPE="NINETEEN_INCH";FAN_PANEL_SECTION="LEFT";FAN_SIZE_MM=80;FAN_HOLE_SPACING=71.5;FANS_PER_SECTION=1;FAN_PANEL_RACK_UNITS=2],\
    scad/assemblies/faceplate/fan/fan_panel.scad[FAN_PANEL_RACK_TYPE="NINETEEN_INCH";FAN_PANEL_SECTION="MIDDLE";FAN_SIZE_MM=80;FAN_HOLE_SPACING=71.5;FANS_PER_SECTION=1;FAN_PANEL_RACK_UNITS=2],\
    scad/assemblies/faceplate/fan/fan_panel.scad[FAN_PANEL_RACK_TYPE="NINETEEN_INCH";FAN_PANEL_SECTION="RIGHT";FAN_SIZE_MM=80;FAN_HOLE_SPACING=71.5;FANS_PER_SECTION=1;FAN_PANEL_RACK_UNITS=2]
BUILDSCAD_LOG_LEVEL=INFO
BUILDSCAD_OPENSCAD_PATH=openscad-nightly
BUILDSCAD_OUTPUT_FORMAT=stl,png,3mf
BUILDSCAD_OPENSCAD_COLORSCHEME=DeepOcean
BUILDSCAD_IMAGESIZE=1280,720
