BUILDSCAD_PROJECT=openRack
BUILDSCAD_VERSION=0.0.1
BUILDSCAD_AUTHOR=dduxx
BUILDSCAD_ASSEMBLIES=scad/assemblies/rack_studs/bracket.scad,\
    scad/assemblies/rack_studs/nut.scad,\
    scad/assemblies/hdd/sled.scad[SLED_TYPE="default"],\
    scad/assemblies/hdd/sled.scad[SLED_TYPE="2_5_adapter"],\
    scad/assemblies/hdd/jbod.scad[SECTION="LEFT"],\
    scad/assemblies/hdd/jbod.scad[SECTION="MIDDLE"],\
    scad/assemblies/hdd/jbod.scad[SECTION="RIGHT"]
BUILDSCAD_LOG_LEVEL=DEBUG
BUILDSCAD_OPENSCAD_PATH=openscad-nightly
BUILDSCAD_OUTPUT_FORMAT=stl,png,3mf
BUILDSCAD_OPENSCAD_COLORSCHEME=DeepOcean
