BUILDSCAD_PROJECT=openRack
BUILDSCAD_VERSION=0.0.1
BUILDSCAD_AUTHOR=dduxx
BUILDSCAD_ASSEMBLIES=scad/assemblies/rack_studs/bracket.scad,\
    scad/assemblies/rack_studs/nut.scad,\
    scad/assemblies/hdd/sled.scad[TWO_POINT_FIVE_ADAPTER=false],\
    scad/assemblies/hdd/sled.scad[TWO_POINT_FIVE_ADAPTER=true],\
    scad/assemblies/hdd/sled_cover.scad
BUILDSCAD_LOG_LEVEL=DEBUG
BUILDSCAD_OPENSCAD_PATH=openscad-nightly
BUILDSCAD_OUTPUT_FORMAT=stl,png,3mf
BUILDSCAD_OPENSCAD_COLORSCHEME=DeepOcean
