THREE_POINT_FIVE_HDD_WIDTH = 101.85;
THREE_POINT_FIVE_HDD_DEPTH = 147;
THREE_POINT_FIVE_HDD_HEIGHT = 27;

TWO_POINT_FIVE_HDD_WIDTH = 70.1;
TWO_POINT_FIVE_HDD_DEPTH = 101.85;
TWO_POINT_FIVE_HDD_HEIGHT = 15;

HDD_BOTTOM_HOLE_EDGE_OFFSET = 3.43;
