include <../utils/unit_conversion.scad>

THREE_POINT_FIVE_INCH_DRIVE_DIMENSIONS = [101.6, 147, 26.1];
THREE_POINT_FIVE_INCH_MOUNT_POINTS = [[], [], []];
TWO_POINT_FIVE_INCH_DRIVE_DIMENSIONS = [69.85, 100, 12.5];
